### ISSUE TITLE
pymagicc fails with pandas.errors.ParserError

### ISSUE THREAD

**Issue by matthiasmengel** [openclimatedata/pymagicc#92]
I want to run pymagicc with a custom executable. I do

```
export MAGICC_EXECUTABLE_6=/home/mengel/projects/magicc/run/magicc
```
and then
python test.py

with test.py being
```
import pymagicc
from pymagicc import rcp26
pymagicc.run(rcp26)
```

This fails with the following error:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    pymagicc.run(rcp26)
  File "/home/mengel/projects/pymagicc/pymagicc/__init__.py", line 316, in run
    results = magicc.run()
  File "/home/mengel/projects/pymagicc/pymagicc/api.py", line 190, in run
    engine="python",
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2266, in read
    alldata = self._rows_to_cols(content)
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2909, in _rows_to_cols
    self._alert_malformed(msg, row_num + 1)
  File "/home/mengel/anaconda3/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2676, in _alert_malformed
    raise ParserError(msg)
pandas.errors.ParserError: Expected 2 fields in line 22, saw 6. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.
```

I checked for the `magicc.run_dir`, said to be `/tmp/pymagicc-6bwh2x53/run`, but such directory does not exist.

Before digging deeper into this, do you have an idea how to resolve?

Ubuntu 16.04, conda with the following packages:

```
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                   py36_2    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
automat                   0.7.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.4                      py_1    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cftime                    1.0.1            py36h7eb728f_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
curl                      7.61.0               h93b3f91_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
f90nml                    1.0.2                     <pip>
fontconfig                2.13.0               h65d0f4c_5    conda-forge
freetype                  2.9.1                h6debe1e_1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
h5py                      2.8.0            py36hb794570_1    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hc401514_1    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_2    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.0                      py_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
joblib                    0.12.2                     py_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.14.6                        0    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 h470a237_2    conda-forge
libnetcdf                 4.6.1                he6cff42_7    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.35               ha92aebf_0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libuuid                   2.32.1               h470a237_0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_3    conda-forge
mako                      1.0.7                      py_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.3            py36h8e2386c_0    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
mkl                       2018.0.3                      1  
mkl-service               1.1.2            py36h651fb7a_4  
more-itertools            4.3.0                    py36_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf4                   1.4.1            py36h62672b6_0    conda-forge
notebook                  5.6.0                    py36_0    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1  
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.2.2                         1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
patsy                     0.5.0                      py_1    conda-forge
pcre                      8.41                 h470a237_2    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
prometheus_client         0.3.0                      py_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
py                        1.5.4                      py_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycparser                 2.18                       py_1    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pygpu                     0.7.6                    py36_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pymc3                     3.5                      py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0            py36h8210e8a_6    conda-forge
pytest                    3.7.2                    py36_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
qtconsole                 4.4.1            py36h8a2030e_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
scipy                     1.1.0           py36_blas_openblash7943236_201  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
statsmodels               0.9.0                    py36_0    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
theano                    1.0.2                    py36_0    conda-forge
tk                        8.6.8                         0    conda-forge
tornado                   5.1              py36h470a237_1    conda-forge
tqdm                      4.24.0                     py_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
twisted                   18.7.0           py36h14c3975_1  
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
widgetsnbextension        3.4.0                    py36_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope.interface            4.5.0            py36h470a237_0    conda-forge
```

**Comment by rgieseke** [comment]
Should maybe be set as `MAGICC_EXECUTABLE_7` as you likely compiled a recent development version with new APIs?

**Comment by rgieseke** [comment]
To properly debug such issues it should be easier to set up things step by step as in the `run` function:

https://github.com/openclimatedata/pymagicc/blob/master/pymagicc/__init__.py#L283

(You can also use `MAGICC7()`)

There you can also define and inspect a `run_dir` directory more easily.

**Comment by matthiasmengel** [comment]
This may be because `f90nml.write(data, fname, force=True)` in `MAGICCBase.set_config(...)` wants to write a file to `/tmp/pymagicc-...`. A directory that seems never be created.

**Comment by rgieseke** [comment]
`run` doesn't take a `root_dir` parameter, you need to set this up with the API functions. Sorry, this isn't particularly well documented yet.

Something like

```python
with MAGICC7(root_dir='YOUR_BINARY') as magicc:
       # Write out the `Scenario` as a .SCEN-file.
        write_scen_file(scenario, os.path.join(magicc.run_dir, "SCENARIO.SCEN"))

        year_cfg = {}
        if "startyear" in kwargs:
            year_cfg["startyear"] = kwargs.pop("startyear")
        if "endyear" in kwargs:
            year_cfg["endyear"] = kwargs.pop("endyear")
            magicc.set_years(**year_cfg)
        kwargs.setdefault("file_emissionscenario", "SCENARIO.SCEN")
        magicc.set_config(**kwargs)

        results = magicc.run()
```

If you set `root_dir` it will not create copy and work directly in your MAGICC directory.
You can also use `create_copy` to manually create a copy.

**Comment by matthiasmengel** [comment]
Good to know, thanks! This works. I think it would be better to have this in `pymagicc.run(...)` directly, which is the highest level access to pymaggic. We do not want to fiddle with the source code for configuration if we can avoid it, right?

**Comment by rgieseke** [comment]
I think we just need better docs. We could potentially discuss if we have to many possibilities to do similar things, with feedback from like @matthiasmengel's
